query($criteria: SummaryCriteria) {
  AllProductionSummary(input: $criteria) {
    id
    location
    centralNo
    inverterNo
    lastOneHour
    lastTwoHour
    workingHour
    forToday
    yesterdayProduction
    lastWeek
    montly
    status
    progress {
      stringsCount
      workedStrings
      strings {
        id
        name
        value
      }
    }
  }
}
